# This is a basic workflow to help you get started with Actions

name: NuGet Package
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/Armitxes/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o package  

      - name: Push package to GitHub
        run: dotnet nuget push ./package/*.nupkg --api-key "${{secrets.GH_PACKAGE}}" --source "github" --skip-duplicate
